.PHONY: clean All

All:
	@echo "----------Building project:[ Section-Challenge - Debug ]----------"
	@cd "Section-Challenge" && "$(MAKE)" -f  "Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section-Challenge - Debug ]----------"
	@cd "Section-Challenge" && "$(MAKE)" -f  "Section-Challenge.mk" clean
