.PHONY: clean All

All:
	@echo "----------Building project:[ Section-13-Challenge - Debug ]----------"
	@cd "Section-13-Challenge" && "$(MAKE)" -f  "Section-13-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section-13-Challenge - Debug ]----------"
	@cd "Section-13-Challenge" && "$(MAKE)" -f  "Section-13-Challenge.mk" clean
